

export const metadata = {
  title: 'API Dashboard Bupati',
  description: 'Generated by Dashboard Developer',
  icons: {
    icon: '/tapsel-logo.png',
    apple: '/tapsel-logo.png',
  },
  openGraph: {
    images: ['/tapsel-logo.png'],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
