### Baca Semua Data Stunting
GET http://localhost:3001/api/keseheatanmasyarakat/3stunting
Content-Type: application/json
x-api-key: dashtbrndfiorkddnskjfirirkfkfdkfk

###

### Buat Data Stunting Baru
POST http://localhost:3001/api/keseheatanmasyarakat/3stunting
Content-Type: application/json
x-api-key: dashtbrndfiorkddnskjfirirkfkfdkfk

{
    "kdkecamatan": 2,
    "nmkecamatan": "Angkola Selatan",
    "tahun": 2023,
    "jumlahBalita": 3800,
    "balitaStunting": 760,
    "persentase": 20
}
###

### Baca Data Stunting Berdasarkan ID
GET http://localhost:3001/api/keseheatanmasyarakat/3stunting/1
Content-Type: application/json
x-api-key: dashtbrndfiorkddnskjfirirkfkfdkfk

###

### Update Data Stunting
PUT http://localhost:3001/api/keseheatanmasyarakat/3stunting/1
Content-Type: application/json
x-api-key: dashtbrndfiorkddnskjfirirkfkfdkfk

{
    "kdkecamatan": 2,
    "nmkecamatan": "Angkola Selatan",
    "tahun": 2023,
    "jumlahBalita": 3800,
    "balitaStunting": 760,
    "persentase": 20
}

###

### Hapus Data Stunting
DELETE http://localhost:3001/api/keseheatanmasyarakat/3stunting/1
Content-Type: application/json
x-api-key: dashtbrndfiorkddnskjfirirkfkfdkfk

###
